# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'aboutGUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_about(object):
    def setupUi(self, about):
        about.setObjectName("about")
        about.resize(400, 300)
        self.textEdit = QtWidgets.QTextEdit(about)
        self.textEdit.setGeometry(QtCore.QRect(0, 0, 401, 301))
        self.textEdit.setObjectName("textEdit")

        self.retranslateUi(about)
        QtCore.QMetaObject.connectSlotsByName(about)

    def retranslateUi(self, about):
        _translate = QtCore.QCoreApplication.translate
        about.setWindowTitle(_translate("about", "关于compiler"))
