# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'helpGUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_help(object):
    def setupUi(self, help):
        help.setObjectName("help")
        help.resize(400, 300)
        self.textEdit = QtWidgets.QTextEdit(help)
        self.textEdit.setGeometry(QtCore.QRect(3, 6, 391, 291))
        self.textEdit.setObjectName("textEdit")

        self.retranslateUi(help)
        QtCore.QMetaObject.connectSlotsByName(help)

    def retranslateUi(self, help):
        _translate = QtCore.QCoreApplication.translate
        help.setWindowTitle(_translate("help", "帮助"))
